<?php
$title = $this->translate('角色管理');
$this->headTitle($title);

?>
<?php if ($flashMessages): ?>
<div class="alert alert-info">
    <a class="close" data-dismiss="alert" href="#">&times;</a>
    <ul>
    <?php foreach ($flashMessages as $flashMessage): ?>
        <li><?php echo $this->escapeHtml($flashMessage) ?></li>
    <?php endforeach ?>
    </ul>
</div>
<?php endif ?>

<h3><?php echo $this->escapeHtml($title) ?></h3>

<p>
    <a class="btn" href="<?php echo $this->url('atansuser/role/add') ?>">
        <i class="icon-plus-sign"></i>
        <?php echo $this->translate('新增') ?>
    </a>
</p>

<?php if (count($roles) > 0) : ?>
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th class="span1">#</th>
                <th class="span2"><?php echo $this->translate('角色') ?></th>
                <th class="span8"><?php echo $this->translate('權限') ?></th>
                <th class="span1"><?php echo $this->translate('操作') ?></th>
            </tr>
        </thead>
        <tbody>
            <?php
            foreach ($roles as $role) {
                echo $this->partial('atans-user/role/partial', array('role' => $role));
            }
            ?>
        </tbody>
    </table>
<?php else: ?>
    <div class="alert">
        <h4><?php echo $this->translate('找不到任何角色') ?></h4>
    </div>
<?php endif ?>