<?php
use AtansUser\Module;

$title = $this->translate('Add user', Module::TRANSLATOR_TEXT_DOMAIN);
$this->headTitle($title);

/**
 * @var \Zend\Form\Form $form
 */
$form = $this->form;
$form->setAttribute('action', $this->url('zfcadmin/user/add'));
$form->prepare();
?>

<h4 class="page-header">
    <span class="glyphicon glyphicon-plus"></span>
    <?php echo $this->escapeHtml($title) ?>

    <small class="pull-right">
        <a href="<?php echo $this->url('zfcadmin/user')?>">
            <?php echo $this->translate('User management', Module::TRANSLATOR_TEXT_DOMAIN) ?>
        </a>
        &gt; <?php echo $this->escapeHtml($title) ?>
    </small>
</h4>

<?php echo $this->form()->openTag($form) ?>
    <div class="panel panel-default">
        <div class="panel-body">
            <?php $inputFilter = $form->getInputFilter(); ?>
            <?php foreach ($form as $element): ?>
                <?php if ($element instanceof \Zend\Form\Element\Hidden): ?>
                    <?php echo $this->formElement($element) ?>
                <?php else: ?>
                    <?php $elementMessages = $element->getMessages(); ?>
                    <div class="form-group <?php echo ($elementMessages ? ' has-error':'')?>">
                        <div class="control-label col-lg-3 col-md-3 col-sm-3">
                            <?php if ($inputFilter->get($element->getName())->isRequired()): ?>
                            <span class="text-danger">*</span>
                            <?php endif ?>

                            <?php echo $this->escapeHtml($this->translate($element->getLabel(), Module::TRANSLATOR_TEXT_DOMAIN)) ?>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6">
                            <?php echo $this->formElement($element) ?>

                            <?php if ($elementMessages): ?>
                            <div class="help-block">
                                <?php echo $this->htmlList($elementMessages, false, array('class' => 'list-unstyled')) ?>
                            </div>
                            <?php endif ?>
                        </div>
                    </div>
                <?php endif ?>
            <?php endforeach ?>
        </div>
        <div class="panel-footer">
            <div class="row">
                <div class="col-lg-offset-3 col-md-offset-3 col-sm-offset-3 col-lg-6 col-md-6 col-sm-6">
                    <button class="btn btn-primary" type="submit">
                        <?php echo $this->translate('Submit', Module::TRANSLATOR_TEXT_DOMAIN) ?>
                    </button>
                    <a class="btn btn-default" href="<?php echo $this->url('zfcadmin/user') ?>">
                        <?php echo $this->translate('Cancel', Module::TRANSLATOR_TEXT_DOMAIN) ?>
                    </a>
                </div>
            </div>
        </div>
    </div>
<?php echo $this->form()->closeTag() ?>
