<?php
use AtansUser\Module;

$title = $this->translate('Delete user', Module::TRANSLATOR_TEXT_DOMAIN);
$this->headTitle($title);
?>

<h4 class="page-header">
    <span class="glyphicon glyphicon-remove"></span>
    <?php echo $this->escapeHtml($title) ?>

    <small class="pull-right">
        <a href="<?php echo $this->url('zfcadmin/user')?>">
            <?php echo $this->translate('User management', Module::TRANSLATOR_TEXT_DOMAIN) ?>
        </a>
        &gt; <?php echo $this->escapeHtml($title) ?>
    </small>
</h4>

<form action="<?php echo $this->url('zfcadmin/user/delete', array('id' => $user->getId())) ?>" method="post">

    <input name="delete" type="hidden" value="Yes">

    <div class="panel panel-default">
        <div class="panel-body">
                <?php echo sprintf($this->translate("Are you sure you want to delete user '%s'?", Module::TRANSLATOR_TEXT_DOMAIN), $user->getUsername())?>
        </div>
        <div class="panel-footer">
            <button class="btn btn-danger" type="submit">
                <?php echo $this->translate('Delete', Module::TRANSLATOR_TEXT_DOMAIN) ?>
            </button>
            <a class="btn btn-default" href="<?php echo $this->url('zfcadmin/user') ?>">
                <?php echo $this->translate('Cancel', Module::TRANSLATOR_TEXT_DOMAIN) ?>
            </a>
        </div>
    </div>
</form>
