<?php
use AtansUser\Controller\UserAdminController;
use AtansUser\Module;

$title = $this->translate('User Management', Module::TRANSLATOR_TEXT_DOMAIN);
$this->headTitle($title);

/**
 * @var \Zend\Form\Form $form
 */
$form = $this->form;
?>

<?php echo $this->render('alert/bootstrap', array('namespace' => UserAdminController::FLASHMESSENGER_NAMESPACE))?>

<h4 class="page-header">
    <span class="glyphicon glyphicon-user"></span>
    <?php echo $this->escapeHtml($title) ?>
</h4>

<div class="panel panel-default">
    <div class="panel-heading">
        <div class="btn-group btn-group-sm">
            <a class="btn btn-default" href="<?php echo $this->url('zfcadmin/user/add') ?>">
                <i class="glyphicon glyphicon-plus"></i>
                <?php echo $this->translate('Add user', Module::TRANSLATOR_TEXT_DOMAIN) ?>
            </a>
        </div>

        <div class="btn-group btn-group-sm pull-right">
            <a class="btn btn-default" href="<?php echo $this->url('zfcadmin/user/role') ?>">
                <?php echo $this->escapeHtml($this->translate('Role Management', Module::TRANSLATOR_TEXT_DOMAIN)) ?>
            </a>
            <a class="btn btn-default" href="<?php echo $this->url('zfcadmin/user/permission') ?>">
                <?php echo $this->escapeHtml($this->translate('Permission Management', Module::TRANSLATOR_TEXT_DOMAIN)) ?>
            </a>
        </div>
    </div>
    <?php if (count($paginator) > 0) : ?>
        <div class="panel-body">
            <?php echo $this->render('atans-user/user-admin/search-form', array('form' => $form)) ?>
        </div>
        <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th class="col-lg-1 col-md-1 col-sm-1">#</th>
                    <th class="col-lg-3 col-md-3 col-sm-3"><?php echo $this->translate('Username', Module::TRANSLATOR_TEXT_DOMAIN) ?></th>
                    <th class="col-lg-3 col-md-3 col-sm-3"><?php echo $this->translate('Roles', Module::TRANSLATOR_TEXT_DOMAIN) ?></th>
                    <th class="col-lg-2 col-md-2 col-sm-2"><?php echo $this->translate('Status', Module::TRANSLATOR_TEXT_DOMAIN) ?></th>
                    <th class="col-lg-2 col-md-2 col-sm-2"><?php echo $this->translate('Actions', Module::TRANSLATOR_TEXT_DOMAIN) ?></th>
                </tr>
            </thead>
            <?php
            foreach ($paginator as $user) {
                echo $this->partial('atans-user/user-admin/partial', array('user' => $user));
            }
            ?>
        </table>
    <?php else: ?>
        <div class="panel-body">
            <div class="panel-body">
                <?php echo $this->render('atans-user/user-admin/search-form', array('form' => $form)) ?>
            </div>
            <br>

            <div class="alert alert-info">
                <?php echo $this->translate('Could not find any users', Module::TRANSLATOR_TEXT_DOMAIN) ?>
            </div>
        </div>
    <?php endif ?>
</div>

<?php
echo $this->paginationControl(
    $this->paginator,
    'Sliding',
    'pagination/query',
    array(
        'route' => 'zfcadmin/user',
        'options' => array(
            'query' => $form->getData(),
        ),
    )
);
?>
