<?php
namespace AtansUser;

use AtansUser\Entity\User;

switch ($user->getStatus()) {
    case User::STATUS_ACTIVE :
        $status = $this->translate('Active', __NAMESPACE__);
        $statusClass = ' label-success';
        break;
    case User::STATUS_INACTIVE :
        $status = $this->translate('Inactive', __NAMESPACE__);
        $statusClass = ' label-warning';
        break;
    case User::STATUS_DELETED :
        $status = $this->translate('Deleted', __NAMESPACE__);
        $statusClass = ' label-danger';
        break;
    default :
        $status = sprintf($this->translate("Unknown status '%s'"), $user->getStatus());
        $statusClass = ' label-danger';
}

$roles = $user->getRoles()
?>
<tr id="user-<?php echo $this->escapeHtmlAttr($user->getId()) ?>" data-id="<?php echo $this->escapeHtmlAttr($user->getId()) ?>">
    <td>
        <?php echo $this->escapeHtml($user->getId()) ?>
    </td>
    <td>
        <?php echo $this->escapeHtml($user->getUserName()) ?>
    </td>
    <td>
        <?php if (count($roles)): ?>
            <ul class="list-unstyled">
                <?php foreach ($roles as $role): ?>
                <li><?php echo $role->getName() ?></li>
                <?php endforeach ?>
            </ul>
        <?php else: ?>
            <span class="label label-warning">
                <?php echo $this->escapeHtml($this->translate('None', __NAMESPACE__)) ?>
            </span>
        <?php endif ?>
    </td>
    <td>
        <span class="label<?php echo $statusClass?>">
            <?php echo $this->escapeHtml($status) ?>
        </span>
    </td>
    <td>
        <div class="btn-group btn-group-sm">
            <a class="btn btn-default" href="<?php echo $this->url('zfcadmin/user/edit', array('id' => $user->getId())) ?>">
                <span class="glyphicon glyphicon-edit"></span>
            </a>
            <a class="btn btn-default" href="<?php echo $this->url('zfcadmin/user/delete', array('id' => $user->getId())) ?>">
                <span class="glyphicon glyphicon-remove"></span>
            </a>
        </div>
    </td>
</tr>
