<?php
/**
 * @var \Zend\Form\Form $form
 */
$form = $this->form;
$form->setAttribute('action', $this->url('zfcadmin/user'));
$form->prepare();
?>
<?php echo $this->form()->openTag($form) ?>

    <div class="form-group">
        <?php echo $this->formElement($form->get('count')) ?>
    </div>

    <div class="form-group">
        <?php echo $this->formElement($form->get('status')) ?>
    </div>

    <div class="form-group">
        <?php echo $this->formElement($form->get('query')) ?>
        <button class="btn btn-default">
            <span class="glyphicon glyphicon-search"></span>
        </button>
    </div>

<?php echo $this->form()->closeTag() ?>