<?php
use AtansUser\Module;

/**
 * @var \AtansUser\Entity\Permission
 */
$permission = $this->permission;

$title = $this->translate('Delete permission', Module::TRANSLATOR_TEXT_DOMAIN);
$this->headTitle($title);
?>

<h4 class="page-header">
    <span class="glyphicon glyphicon-remove"></span>
    <?php echo $this->escapeHtml($title) ?>

    <small class="pull-right">
        <a href="<?php echo $this->url('zfcadmin/user')?>">
            <?php echo $this->translate('User Management', Module::TRANSLATOR_TEXT_DOMAIN) ?>
        </a>
        &gt;
        <a href="<?php echo $this->url('zfcadmin/user')?>">
            <?php echo $this->translate('Permission Management', Module::TRANSLATOR_TEXT_DOMAIN) ?>
        </a>
        &gt;
        <?php echo $this->escapeHtml($title) ?>
    </small>
</h4>

<form action="<?php echo $this->url('zfcadmin/user/permission/delete', array('id' => $permission->getId())) ?>" method="post">

    <input name="delete" type="hidden" value="Yes">
    <div class="panel panel-default">
        <div class="panel-body">
            <?php echo sprintf($this->translate("Are your sure you want to delete permission '%s'?", Module::TRANSLATOR_TEXT_DOMAIN), $permission->getName())?>
        </div>
        <div class="panel-footer">
            <button class="btn btn-danger" type="submit">
                <?php echo $this->translate('Delete', Module::TRANSLATOR_TEXT_DOMAIN) ?>
            </button>
            <a class="btn btn-default" href="<?php echo $this->url('zfcadmin/user/permission') ?>">
                <?php echo $this->translate('Cancel', Module::TRANSLATOR_TEXT_DOMAIN) ?>
            </a>
        </div>
    </div>
</form>
