<?php
use AtansUser\Controller\PermissionAdminController;
use AtansUser\Module;

$title = $this->translate('Permission Management', Module::TRANSLATOR_TEXT_DOMAIN);
$this->headTitle($title);

/**
 * @var \Zend\Form\Form $form
 */
$form = $this->form;

/**
 * @var \Zend\Paginator\Paginator $paginator
 */
$paginator = $this->paginator;

echo $this->render('alert/bootstrap', array('namespace' => PermissionAdminController::FLASHMESSENGER_NAMESPACE));
?>

<h4 class="page-header">
    <?php echo $this->escapeHtml($title) ?>

    <small class="pull-right">
        <a href="<?php echo $this->url('zfcadmin/user')?>">
            <?php echo $this->translate('User Management', Module::TRANSLATOR_TEXT_DOMAIN) ?>
        </a>
        &gt;
        <?php echo $this->escapeHtml($title) ?>
    </small>
</h4>

<div class="panel panel-default">
    <div class="panel-heading">
        <a class="btn btn-default btn-sm" href="<?php echo $this->url('zfcadmin/user/permission/add') ?>">
            <i class="glyphicon glyphicon-plus"></i>
            <?php echo $this->translate('Add permission', Module::TRANSLATOR_TEXT_DOMAIN) ?>
        </a>
    </div>
    <?php if (count($paginator) > 0) : ?>
        <div class="panel-body">
            <?php echo $this->render('atans-user/permission-admin/search-form', array('form' => $form)) ?>
        </div>

        <table class="table table-bordered table-hover">
            <thead>
            <tr>
                <th class="col-lg-1 col-md-1 col-sm-1">#</th>
                <th class="col-lg-4 col-md-4 col-sm-4"><?php echo $this->translate('Permission name', Module::TRANSLATOR_TEXT_DOMAIN) ?></th>
                <th class="col-lg-5 col-md-5 col-sm-5"><?php echo $this->translate('Roles', Module::TRANSLATOR_TEXT_DOMAIN) ?></th>
                <th class="col-lg-2 col-md-2 col-sm-2"><?php echo $this->translate('Actions', Module::TRANSLATOR_TEXT_DOMAIN) ?></th>
            </tr>
            </thead>
            <tbody>
            <?php
            foreach ($paginator as $permission) {
                echo $this->partial('atans-user/permission-admin/partial', array('permission' => $permission));
            }
            ?>
            </tbody>
        </table>
    <?php else: ?>
    <div class="panel-body">
        <?php echo $this->render('atans-user/permission-admin/search-form', array('form' => $form)) ?>
        <br>

        <div class="alert alert-info">
            <?php echo $this->translate('Could not find any permissions', Module::TRANSLATOR_TEXT_DOMAIN) ?>
        </div>
    </div>
    <?php endif ?>
</div>

<?php
echo $this->paginationControl(
    $paginator,
    'Sliding',
    'pagination/query',
    array(
        'route' => 'zfcadmin/user/permission',
        'options' => array(
            'query' => $form->getData(),
        ),
    )
);
?>