<?php
$title = $this->translate('Permission Management');
$this->headTitle($title);

echo $this->render('alert/bootstrap', array('namespace' => 'atansuser-permission-admin-index'));
?>

<h4 class="page-header">
    <?php echo $this->escapeHtml($title) ?>
    <small class="pull-right">
        <a href="<?php echo $this->url('zfcadmin/user')?>"><?php echo $this->translate('User management') ?></a> &gt; <?php echo $this->escapeHtml($title) ?>
    </small>
</h4>

    <p>
        <a class="btn btn-default" href="<?php echo $this->url('zfcadmin/user/permission/add') ?>">
            <i class="glyphicon glyphicon-plus"></i>
            <?php echo $this->translate('Add permission') ?>
        </a>
    </p>

<?php if (count($permissions) > 0) : ?>
    <table class="table table-bordered table-hover">
        <thead>
        <tr>
            <th class="span1">#</th>
            <th class="span5"><?php echo $this->translate('Permission name') ?></th>
            <th class="span5"><?php echo $this->translate('Roles') ?></th>
            <th class="span1"><?php echo $this->translate('Actions') ?></th>
        </tr>
        </thead>
        <tbody>
        <?php
        foreach ($permissions as $permission) {
            echo $this->partial('atans-user/permission-admin/partial', array('permission' => $permission));
        }
        ?>
        </tbody>
    </table>
<?php else: ?>
    <div class="alert">
        <h4><?php echo $this->translate('Could not find any permissions.') ?></h4>
    </div>
<?php endif ?>