<?php
namespace AtansUser;

$title = $this->translate('Permission Management', __NAMESPACE__);
$this->headTitle($title);

echo $this->render('alert/bootstrap', array('namespace' => 'atansuser-permission-admin-index'));
?>

<h4 class="page-header">
    <?php echo $this->escapeHtml($title) ?>

    <small class="pull-right">
        <a href="<?php echo $this->url('zfcadmin/user')?>">
            <?php echo $this->translate('User Management', __NAMESPACE__) ?>
        </a>
        &gt;
        <?php echo $this->escapeHtml($title) ?>
    </small>
</h4>

<div class="panel panel-default">
    <div class="panel-heading">
        <a class="btn btn-default btn-sm" href="<?php echo $this->url('zfcadmin/user/permission/add') ?>">
            <i class="glyphicon glyphicon-plus"></i>
            <?php echo $this->translate('Add permission', __NAMESPACE__) ?>
        </a>
    </div>
    <?php if (count($paginator) > 0) : ?>
        <div class="panel-body">
            <?php echo $this->render('atans-user/permission-admin/search-form', array('form' => $form)) ?>
        </div>

        <table class="table table-bordered table-hover">
            <thead>
            <tr>
                <th class="col-lg-1 col-md-1 col-sm-1">#</th>
                <th class="col-lg-4 col-md-4 col-sm-4"><?php echo $this->translate('Permission name', __NAMESPACE__) ?></th>
                <th class="col-lg-5 col-md-5 col-sm-5"><?php echo $this->translate('Roles', __NAMESPACE__) ?></th>
                <th class="col-lg-2 col-md-2 col-sm-2"><?php echo $this->translate('Actions', __NAMESPACE__) ?></th>
            </tr>
            </thead>
            <tbody>
            <?php
            foreach ($paginator as $permission) {
                echo $this->partial('atans-user/permission-admin/partial', array('permission' => $permission));
            }
            ?>
            </tbody>
        </table>
    <?php else: ?>
    <div class="panel-body">
        <?php echo $this->render('atans-user/permission-admin/search-form', array('form' => $form)) ?>
        <br>

        <div class="alert alert-info">
            <?php echo $this->translate('Could not find any permissions.', __NAMESPACE__) ?>
        </div>
    </div>
    <?php endif ?>
</div>

<?php
if (count($this->paginator)) {
    echo $this->paginationControl(
        $this->paginator,
        'Sliding',
        'pagination/query',
        array(
            'route' => 'zfcadmin/user/permission',
            'options' => array(
                'query' => $form->getData(),
            ),
        )
    );
}
?>