<?php
use AtansUser\Module;

/**
 * @var \AtansUser\Entity\Permission $permission
 */
$permission = $this->permission;
?>
<tr id="permission-<?php echo $this->escapeHtmlAttr($permission->getId()) ?>" data-id="<?php echo $this->escapeHtmlAttr($permission->getId()) ?>">
    <td>
        <?php echo $this->escapeHtml($permission->getId()) ?>
    </td>
    <td>
        <?php echo $this->escapeHtml($permission->getName()) ?>
        <?php if ($description = $permission->getDescription()): ?>
        <br>
        <small class="text-muted">
            <?php echo $this->escapeHtml($description) ?>
        </small>
        <?php endif ?>
    </td>
    <td>
        <?php if (($roles = $permission->getRoles()) && count($roles) > 0): ?>
            <ul class="list-unstyled">
                <?php foreach ($roles as $role) :?>
                <li><?php echo $this->escapeHtml($role->getName()) ?></li>
                <?php endforeach ?>
            </ul>
        <?php else: ?>
            <span class="label label-warning">
                <?php echo $this->translate('None', Module::TRANSLATOR_TEXT_DOMAIN) ?>
            </span>
        <?php endif ?>
    </td>
    <td>
        <div class="btn-group">
            <a class="btn btn-default" href="<?php echo $this->url('zfcadmin/user/permission/edit', array('id' => $permission->getId())) ?>">
                <i class="glyphicon glyphicon-edit"></i>
            </a>
            <a class="btn btn-default" href="<?php echo $this->url('zfcadmin/user/permission/delete', array('id' => $permission->getId())) ?>">
                <i class="glyphicon glyphicon-remove"></i>
            </a>
        </div>
    </td>
</tr>
