<?php
namespace AtansUser;

$form = $this->form;
$form->setAttribute('action', $this->url('zfcadmin/user/permission'));
$form->prepare();
?>
<?php echo $this->form()->openTag($form) ?>

    <div class="form-group">
        <?php echo $this->formElement($form->get('size')) ?>
    </div>

    <div class="form-group">
        <?php echo $this->formElement($form->get('query')) ?>
        <button class="btn btn-default">
            <span class="glyphicon glyphicon-search"></span>
        </button>
    </div>

<?php echo $this->form()->closeTag() ?>