<?php
namespace AtansUser;

$title = $this->translate('User Home', __NAMESPACE__);
$this->headTitle($title);

echo $this->render('alert/bootstrap', array('namespace' => 'atansuser-user-index'));
?>

<h3><?php echo $this->escapeHtml($title) ?></h3>
<hr>

<?php if ($user = $this->identity()) :?>
    <p>
        <strong>
            <?php echo sprintf($this->translate('Hello，%s', __NAMESPACE__), $user->getUsername()) ?>
        </strong>
    </p>
    <p>
        <?php echo $this->translate('Roles', __NAMESPACE__) ?>:
        <?php echo implode(', ', $user->getRoles()) ?>
    </p>

<?php else: ?>
    <a href="<?php echo $this->url('atansuser/login') ?>">
        <?php echo $this->translate('Login', __NAMESPACE__) ?>
    </a>
<?php endif ?>