<?php
$title = $this->translate('User login');
$this->headTitle($title);

$form = $this->form;
$form->setAttribute('action', $this->url('atansuser/login'));
$form->setAttribute('class', 'form-horizontal');
?>

<?php if (!is_null($error)) : ?>
<div class="alert alert-warning">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <?php echo $error ?>
</div>
<?php endif ?>

<?php echo $this->form()->openTag($form) ?>

    <div class="row">
        <div class="col-lg-offset-3 col-md-offset-3 col-sm-offset-2 col-lg-8 col-md-8 col-sm-8">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <?php echo $this->escapeHtml($title) ?>
                </div>
                <div class="panel-body">
                    <?php foreach ($form as $element):
                        $elementMessages = $element->getMessages();
                     ?>
                    <div class="form-group <?php echo ($elementMessages ? ' has-error':'')?>">
                        <div class="control-label col-lg-3 col-md-3 col-sm-3">
                            <?php echo $this->escapeHtml($element->getLabel()) ?>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6">
                            <?php echo $this->formElement($element) ?>
                            <?php if ($elementMessages): ?>
                                <div class="help-block">
                                    <?php echo $this->htmlList($elementMessages, false, array('class' => 'list-inline')) ?>
                                </div>
                            <?php endif ?>
                        </div>
                    </div>
                    <?php endforeach ?>
                </div>
                <div class="panel-footer">
                    <div class="row">
                        <div class="col-lg-offset-3 col-md-offset-3 col-sm-offset-3 col-lg-6 col-md-6 col-sm-6">
                            <button class="btn btn-primary" type="submit">
                                <?php echo $this->translate('Login') ?>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

<?php echo $this->form()->closeTag() ?>
