<?php
use AtansUser\Controller\UserController;
use AtansUser\Module;

$title = $this->translate('User login', Module::TRANSLATOR_TEXT_DOMAIN);
$this->headTitle($title);

/**
 * @var \Zend\Form\Form $form
 */
$form = $this->form;
$form->setAttribute('action', $this->url('atansuser/login'));
$form->setAttribute('class', 'form-horizontal');

if ($this->redirect) {
    $form->get('redirect')->setValue($this->redirect);
}
?>

<?php echo $this->form()->openTag($form) ?>

    <div class="row">
        <div class="col-lg-offset-3 col-md-offset-3 col-sm-offset-2 col-lg-6 col-md-6 col-sm-8">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <?php echo $this->escapeHtml($title) ?>
                </div>
                <div class="panel-body">
                    <?php echo $this->render('alert/bootstrap', array('namespace' => UserController::FLASHMESSENGER_LOGIN_NAMESPACE)) ?>

                    <?php foreach ($form as $element):?>
                        <?php $elementMessages = $element->getMessages(); ?>

                        <?php if ($element instanceof \Zend\Form\Element\Hidden): ?>
                            <?php echo $this->formHidden($element) ?>
                        <?php else: ?>
                        <div class="form-group <?php echo ($elementMessages ? ' has-error':'')?>">
                            <div class="control-label col-lg-3 col-md-3 col-sm-3">
                                <?php echo $this->escapeHtml($this->translate($element->getLabel(), Module::TRANSLATOR_TEXT_DOMAIN)) ?>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-6">
                                <?php echo $this->formElement($element) ?>

                                <?php if ($elementMessages): ?>
                                <div class="help-block">
                                    <?php echo $this->htmlList($elementMessages, false, array('class' => 'list-unstyled')) ?>
                                </div>
                                <?php endif ?>
                            </div>
                        </div>
                        <?php endif ?>
                    <?php endforeach ?>
                </div>
                <div class="panel-footer">
                    <div class="row">
                        <div class="col-lg-offset-3 col-md-offset-3 col-sm-offset-3 col-lg-6 col-md-6 col-sm-6">
                            <button class="btn btn-primary" type="submit">
                                <?php echo $this->translate('Login', Module::TRANSLATOR_TEXT_DOMAIN) ?>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

<?php echo $this->form()->closeTag() ?>
