<?php
namespace AtansUser;

use Zend\Form\Element\Hidden;

$title = $this->translate('User Register', __NAMESPACE__);
$this->headTitle($title);

$form = $this->form;
$form->setAttribute('action', $this->url('atansuser/register'));
$form->setAttribute('class', 'form-horizontal');
?>

<?php echo $this->form()->openTag($form) ?>

<div class="row">
    <div class="col-lg-offset-3 col-md-offset-3 col-sm-offset-2 col-lg-6 col-md-6 col-sm-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <?php echo $this->escapeHtml($title) ?>
            </div>
            <div class="panel-body">
                <?php foreach ($form as $element):
                    $elementMessages = $element->getMessages();
                    ?>
                    <?php if ($element instanceof Hidden): ?>
                        <?php echo $this->formHidden($element) ?>
                    <?php else: ?>
                        <div class="form-group <?php echo ($elementMessages ? ' has-error':'')?>">
                            <div class="control-label col-lg-3 col-md-3 col-sm-3">
                                <?php echo $this->escapeHtml($this->translate($element->getLabel(), __NAMESPACE__)) ?>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-6">
                                <?php echo $this->formElement($element) ?>

                                <?php if ($elementMessages): ?>
                                    <div class="help-block">
                                        <?php echo $this->htmlList($elementMessages, false, array('class' => 'list-unstyled')) ?>
                                    </div>
                                <?php endif ?>
                            </div>
                        </div>
                    <?php endif ?>
                <?php endforeach ?>
            </div>
            <div class="panel-footer">
                <div class="row">
                    <div class="col-lg-offset-3 col-md-offset-3 col-sm-offset-3 col-lg-6 col-md-6 col-sm-6">
                        <button class="btn btn-primary" type="submit">
                            <?php echo $this->translate('Register', __NAMESPACE__) ?>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php echo $this->form()->closeTag() ?>
