<?php
use AtansUser\Controller\RoleAdminController;
use AtansUser\Module;

$title = $this->translate('Role management', Module::TRANSLATOR_TEXT_DOMAIN);
$this->headTitle($title);

/**
 * @var \Zend\Form\Form $form
 */
$form = $this->form;
/**
 * @var \Zend\Paginator\Paginator $paginator
 */
$paginator = $this->paginator;
?>

<?php echo $this->render('alert/bootstrap', array('namespace' => RoleAdminController::FLASHMESSENGER_NAMESPACE)) ?>

<h4 class="page-header">
    <?php echo $this->escapeHtml($title) ?>
    <small class="pull-right">
        <a href="<?php echo $this->url('zfcadmin/user')?>">
            <?php echo $this->translate('User management', Module::TRANSLATOR_TEXT_DOMAIN) ?>
        </a>
        &gt;
        <?php echo $this->escapeHtml($title) ?>
    </small>
</h4>

<div class="panel panel-default">
    <div class="panel-heading">
        <?php if ($this->isGranted('atansuser.admin.role.add')): ?>
        <a class="btn btn-default btn-sm" href="<?php echo $this->url('zfcadmin/user/role/add') ?>">
            <i class="glyphicon glyphicon-plus"></i>
            <?php echo $this->translate('Add role', Module::TRANSLATOR_TEXT_DOMAIN) ?>
        </a>
        <?php endif ?>
    </div>
<?php if ($paginator->getCurrentItemCount() > 0) : ?>
    <div class="panel-body">
        <?php echo $this->render('atans-user/role-admin/search-form', array('form' => $form)) ?>
    </div>
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th class="col-xs-1">#</th>
                <th class="col-xs-2"><?php echo $this->translate('Role', Module::TRANSLATOR_TEXT_DOMAIN) ?></th>
                <th class="col-xs-2"><?php echo $this->translate('Children', Module::TRANSLATOR_TEXT_DOMAIN) ?></th>
                <th class="col-xs-5"><?php echo $this->translate('Permissions', Module::TRANSLATOR_TEXT_DOMAIN) ?></th>
                <th class="col-xs-2"><?php echo $this->translate('Actions', Module::TRANSLATOR_TEXT_DOMAIN) ?></th>
            </tr>
        </thead>
        <tbody>
            <?php
            foreach ($paginator as $role) {
                echo $this->partial('atans-user/role-admin/partial', array('role' => $role));
            }
            ?>
        </tbody>
    </table>
<?php else: ?>
    <div class="panel-body">
        <?php echo $this->render('atans-user/role-admin/search-form', array('form' => $form)) ?>
        <br>
        <div class="alert alert-info">
            <?php echo $this->translate('Could not find any roles', Module::TRANSLATOR_TEXT_DOMAIN) ?>
        </div>
    </div>
<?php endif ?>
</div>

<?php
echo $this->paginationControl(
    $paginator,
    'Sliding',
    'pagination/query',
    array(
        'route' => 'zfcadmin/user/role',
        'options' => array(
            'query' => $form->getData(),
        ),
    )
);
?>