<?php
namespace AtansUser;

use AtansUser\Controller\RoleAdminController;

$title = $this->translate('Role Management', __NAMESPACE__);
$this->headTitle($title);

echo $this->render('alert/bootstrap', array('namespace' => RoleAdminController::FLASHMESSENGER_NAMESPACE));
?>

<h4 class="page-header">
    <?php echo $this->escapeHtml($title) ?>
    <small class="pull-right">
        <a href="<?php echo $this->url('zfcadmin/user')?>">
            <?php echo $this->translate('User Management', __NAMESPACE__) ?>
        </a>
        &gt;
        <?php echo $this->escapeHtml($title) ?>
    </small>
</h4>


<div class="panel panel-default">
    <div class="panel-heading">
        <a class="btn btn-default btn-sm" href="<?php echo $this->url('zfcadmin/user/role/add') ?>">
            <i class="glyphicon glyphicon-plus"></i>
            <?php echo $this->translate('Add role', __NAMESPACE__) ?>
        </a>
    </div>
<?php if (count($paginator) > 0) : ?>
    <div class="panel-body">
        <?php echo $this->render('atans-user/role-admin/search-form', array('form' => $form)) ?>
    </div>
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th class="col-lg-1 col-md-1 col-sm-1">#</th>
                <th class="col-lg-3 col-md-3 col-sm-3"><?php echo $this->translate('Role', __NAMESPACE__) ?></th>
                <th class="col-lg-3 col-md-3 col-sm-3"><?php echo $this->translate('Parent role', __NAMESPACE__) ?></th>
                <th class="col-lg-3 col-md-3 col-sm-3"><?php echo $this->translate('Permissions', __NAMESPACE__) ?></th>
                <th class="col-lg-2 col-md-2 col-sm-2"><?php echo $this->translate('Actions', __NAMESPACE__) ?></th>
            </tr>
        </thead>
        <tbody>
            <?php
            foreach ($paginator as $role) {
                echo $this->partial('atans-user/role-admin/partial', array('role' => $role));
            }
            ?>
        </tbody>
    </table>
<?php else: ?>
    <div class="panel-body">
        <?php echo $this->render('atans-user/role-admin/search-form', array('form' => $form)) ?>
        <br>
        <div class="alert alert-info">
            <?php echo $this->translate('Could not find any roles', __NAMESPACE__) ?>
        </div>
    </div>
<?php endif ?>
</div>

<?php
if (count($this->paginator)) {
    echo $this->paginationControl(
        $this->paginator,
        'Sliding',
        'pagination/query',
        array(
            'route' => 'zfcadmin/user/role',
            'options' => array(
                'query' => $form->getData(),
            ),
        )
    );
}
?>