<?php
namespace AtansUser;
?>
<tr id="role-<?php echo $this->escapeHtmlAttr($role->getId()) ?>" data-id="<?php echo $this->escapeHtmlAttr($role->getId()) ?>">
    <td>
        <?php echo $this->escapeHtml($role->getId()) ?>
    </td>
    <td>
        <?php echo $this->escapeHtml($role->getName()) ?>

    </td>
    <td>
        <?php if ($parentRole = $role->getParentRole()): ?>
            <span class="label label-success">
                <?php echo $this->escapeHtml($parentRole->getName()) ?>
            </span>
        <?php else: ?>
            <?php echo $this->translate('None', __NAMESPACE__) ?>
        <?php endif ?>
    </td>
    <td>
        <?php if ($permissions = $role->getPermissions()): ?>
            <ul class="list-unstyled">
                <?php foreach ($permissions as $permission) :?>
                <li>
                    <?php echo $this->escapeHtml($permission->getName()) ?>
                    <?php if ($description = $permission->getDescription()): ?>
                        <small class="text-muted"><?php echo $this->escapeHtml($description) ?></small>
                    <?php endif ?>
                </li>
                <?php endforeach ?>
            </ul>
        <?php else: ?>
            <span class="label label-warning">
                <?php echo $this->translate('None', __NAMESPACE__) ?>
            </span>
        <?php endif ?>
    </td>
    <td>
        <div class="btn-group">
            <a class="btn btn-default" href="<?php echo $this->url('zfcadmin/user/role/edit', array('id' => $role->getId())) ?>">
                <i class="glyphicon glyphicon-edit"></i>
            </a>
            <a class="btn btn-default" href="<?php echo $this->url('zfcadmin/user/role/delete', array('id' => $role->getId())) ?>">
                <i class="glyphicon glyphicon-remove"></i>
            </a>
        </div>
    </td>
</tr>
