<?php
?>
<tr id="role-<?php echo $this->escapeHtmlAttr($role->getId()) ?>" data-id="<?php echo $this->escapeHtmlAttr($role->getId()) ?>">
    <td>
        <?php echo $this->escapeHtml($role->getId()) ?>
    </td>
    <td>
        <?php echo $this->escapeHtml($role->getName()) ?>
    </td>
    <td>
        <?php if ($permissions = $role->getPermissions()): ?>
            <ul class="unstyled">
                <?php foreach ($permissions as $permission) :?>
                <li>
                    <?php echo $this->escapeHtml($permission->getName()) ?>
                    <?php if ($description = $permission->getDescription()): ?>
                    <small class="muted"><?php echo $this->escapeHtml($description) ?></small>
                    <?php endif ?>
                </li>
                <?php endforeach ?>
            </ul>
        <?php else: ?>
            <span class="label label-warning">
                <?php echo $this->translate('暫無權限') ?>
            </span>
        <?php endif ?>
    </td>
    <td>
        <div class="btn-group">
            <a class="btn" href="<?php echo $this->url('zfcadmin/role/edit', array('id' => $role->getId())) ?>">
                <i class="icon-edit"></i>
            </a>
            <a class="btn" href="<?php echo $this->url('zfcadmin/role/delete', array('id' => $role->getId())) ?>">
                <i class="icon-remove"></i>
            </a>
        </div>
    </td>
</tr>
